# Value overrides created by the rime_agent terraform module.
%{ if false ~}
# NOTE TO DEVELOPERS: do NOT put default values here! Please put those values in the chart's values.yaml file
%{ endif ~}
rimeAgent:
  images:
%{ if length(image_pull_secret_name) > 0 ~}
    imagePullSecrets:
      - name: ${image_pull_secret_name}
%{ endif ~}
    agentImage:
      registry: "${docker_registry}"
      name: "${image}:${version}"

%{ if length(job_manager_server_addr) > 0 ~}
  jobManagerAddr: ${ job_manager_server_addr }
%{ endif ~}
%{ if length(web_server_addr) > 0 ~}
  grpcWebServerAddr: ${ web_server_addr }
%{ endif ~}
%{ if length(agent_manager_server_addr) > 0 ~}
  agentManagerAddr: ${ agent_manager_server_addr }
%{ endif ~}

  modelTestJob:
%{ if length(model_test_job_config_map) > 0 ~}
    configMapName: ${ model_test_job_config_map }
%{ endif ~}
    serviceAccount:
      name: ${ model_test_job_service_account_name }
      annotations: {
        eks.amazonaws.com/role-arn: ${ s3_reader_role_arn }
      }
%{ if length(upload_server_rest_addr) > 0 ~}
    uploadServerAddr: https://${ upload_server_rest_addr }
%{ endif ~}
%{ if length(firewall_server_rest_addr) > 0 ~}
    firewallServerAddr: https://${ firewall_server_rest_addr }
%{ endif ~}
%{ if length(data_collector_rest_addr) > 0 ~}
    dataCollectorAddr: https://${ data_collector_rest_addr }
%{ endif ~}
%{ if length(dataset_manager_server_rest_addr) > 0 ~}
    datasetManagerAddr: https://${ dataset_manager_server_rest_addr }
%{ endif ~}

  launcher:
    requestQueueProxyAddr: ${ request_queue_proxy_addr }

  datadogTagPodAnnotation: '${datadog_tag_pod_annotation}'

jobMonitor:
  logArchival:
    enabled: ${log_archival_config.enable}
%{if log_archival_config.enable ~}
    storageBucketName: ${log_archival_config.bucket_name}
    endpoint: "s3.amazonaws.com"
    type: "s3"
  serviceAccount:
    # Account used by services that need access to blob storage.
    # This account has special priveleges to read and write to S3 bucket used for blob storage.
    annotations: {
      eks.amazonaws.com/role-arn: ${log_archival_config.role_arn}
    }
%{ endif ~}

tls:
  crossplaneEnabled: ${enable_crossplane_tls}
  enableCertManager: ${enable_cert_manager}
